require("plugins.welcome-page")
require("plugins.cmp")
require("plugins.mason")
require("plugins.git")
require("plugins.appearance")
require("plugins.wf")
require("plugins.treesitter")
-- other
require("plugins.render-markdown")
require("plugins.focus")
require("plugins.telescope")
require("plugins.texpresso")
require("plugins.nvim-autopairs")
require("plugins.global-note")
require("plugins.misc")
